### ISSUE TITLE
Assess Data & Create Report: Diagnosis File

### ISSUE THREAD

**Issue by Josephkworden** [MeghnaMSCS/BMI-6016-Chronic-Cough#2]

**Comment by Kimballa05** [comment]
[Data Quality Assessment of Diagnosis File.docx](https://github.com/MeghnaMSCS/BMI-6016-Chronic-Cough/files/11193317/Data.Quality.Assessment.of.Diagnosis.File.docx)
Here is the Assessment of the Diagnosis File. It's still incomplete pending Siwei's contribution but this is the bulk of what I was able to assess.

**Comment by Siwei-Zhou** [comment]
[
[Data.Quality.Assessment.of.Diagnosis.File.docx](https://github.com/MeghnaMSCS/BMI-6016-Chronic-Cough/files/11207193/Data.Quality.Assessment.of.Diagnosis.File.docx)
](url)

2nd version
There is still something need to be modified.

**Comment by Siwei-Zhou** [comment]
[Data.Quality.Assessment.of.Diagnosis.File (1).docx](https://github.com/MeghnaMSCS/BMI-6016-Chronic-Cough/files/11216770/Data.Quality.Assessment.of.Diagnosis.File.1.docx)


3nd version of Diagnosis data.
This should be complete before merge.
